version: '3'
services:
  dms:
    environment:
     - NODE_ENV=production
    container_name: dms-app
    restart: always
    build: .
    ports:
      - '7000:7000'
    links:
      - mongo  
  mongo:
    environment:
     - NODE_ENV=production
    container_name: mongo 
    command: mongod --port 27018
    image: mongo
    ports:
      - '27018:27018'   